---
- name: Normalized name for management server local ip if on dc_1
  cache:
    key: 'local_mgmt_ip'
    value: "{{ hostvars[groups['dc_1_ms'][0]][interface_name].ipv4.address }}"
  when: groups['dc_1'] is defined and groups['dc_1_ms'] is defined and inventory_hostname in groups['dc_1'] and hostvars[groups['dc_1_ms'][0]][interface_name].ipv4.address is defined

- name: Normalized name for management server local ip if on dc_2
  cache:
    key: 'local_mgmt_ip'
    value: "{{ hostvars[groups['dc_2_ms'][0]][interface_name].ipv4.address }}"
  when: groups['dc_2'] is defined and groups['dc_2_ms'] is defined and inventory_hostname in groups['dc_2'] and hostvars[groups['dc_1_ms'][0]][interface_name].ipv4.address is defined

- name: Normalized name for management server local ip to dc_1 if current node is not on dc_1 or dc_2
  cache:
    key: 'local_mgmt_ip'
    value: "{{ hostvars[groups['dc_1_ms'][0]][interface_name].ipv4.address }}"
  when: local_mgmt_ip is not defined or local_mgmt_ip | trim | length == 0
